# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9d8e6652e7c277350e62bc2ecff165bc"
name = "Gift box tier 2"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
